# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: localhost
  become: yes
  tasks:
    - name: Update Segment
      nsxt_segment:
        hostname: "default"
        username: "default"
        password: "default"
        validate_certs: False
        display_name: test-seg-4
        state: present
        domain_name: dn1
        transport_zone_display_name: "1-transportzone-730"
        subnets:
          - gateway_address: "40.1.1.1/16"
        segment_ports:
          - display_name: test-sp-1
            state: present
          - display_name: test-sp-2
            state: present
          - display_name: test-sp-3
            state: present